---
title: "CB4D Model Diagnostics"
subtitle: "Volume 2"
author: "`r Sys.getenv('USERNAME')`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  word_document:
    toc: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results = 'asis', echo = FALSE, warning = FALSE)
```

**Model run:**
```{r}
fn_i <- tools::file_path_sans_ext(basename(i))
# replace tilde so don't get superscript
fn_i <- gsub("\\~", "\\\\~", fn_i)
cat(fn_i)
```

# 1.0 Meta Information
```{r}
tbl_01
```

# 2.0 Model Map
```{r}
if (format_rmd == "html") {
  M2
} else {
  M2_static
}## IF ~ format_rmd
```

# 3.0 Model Summary
```{r}
tbl_03_00
cat("\n\n")
tbl_03_01
cat("\n\n")
tbl_03_02
```

# 7.0 Station Observation Count
```{r}
tbl_cross_tab
```

# 8.0 Station Diagnostic Plots
```{r}

# ls_faceted[[1]]
# print(ls_faceted[[2]])
# plotly::ggplotly(ls_faceted[[3]])
#plot(1:10, 1:10)
# Print Plots
for (ss in seq_len_station_vec) {
  if (format_rmd == "html") {
    print(ls_faceted[[ss]])
  } else {
    print(ls_faceted[[ss]])
  }## IF ~ format_rmd
  
  cat("\n\n")
}## FOR ~ ss

```

# 9.0 Station Time Series
```{r}
# Print Plots
for (s_p5 in seq_len_station_vec) {
  if (format_rmd == "html") {
    print(ls_p5[[s_p5]])
  } else {
    print(ls_p5[[s_p5]])
  }## IF ~ format_rmd
  
  cat("\n\n")
}## FOR ~ s_p5
```


