---
title: "CB4D Model Diagnostics"
subtitle: "Volume 1"
author: "`r Sys.getenv('USERNAME')`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  word_document:
    toc: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results = 'asis', echo = FALSE, warning = FALSE)
```

**Model run:**
```{r}
fn_i <- tools::file_path_sans_ext(basename(i))
# replace tilde so don't get superscript
fn_i <- gsub("\\~", "\\\\~", fn_i)
cat(fn_i)
```

# 1.0 model meta information
```{r}
tbl_01
```

# 2.0 model map
```{r}
if (format_rmd == "html") {
  M1
} else {
  M1_static
}## IF ~ format_rmd
```

# 3.0 model summary
```{r}
tbl_03_00
cat("\n\n")
tbl_03_01
cat("\n\n")
tbl_03_02
```

# 4.0 statistics by station
```{r}
tbl_04_01
```

# 5.0 simple diagnostic plots
```{r}
plot_05_01
cat("\n\n")
plot_05_02
```

# 6.0 gratia::draw
```{r}
# Print Plots
for (bb in group_n_seqlen) {
  print(ls_gratia[[bb]])
  cat("\n\n")
}## FOR ~ b
```

# 7.0 contingency table
```{r}
tbl_07_01
```



