name: R package binary build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Configure RSPM for pre-built binaries
      - name: Configure CRAN mirror to RSPM
        run: |
          echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/jammy/latest"))' >> ~/.Rprofile

      # Install system dependencies for GSL, OpenMP, and build tools
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgsl-dev libomp-dev build-essential gcc gfortran

      # Set up library paths for the linker
      - name: Configure Library Paths
        run: |
          echo "/usr/lib/x86_64-linux-gnu" | sudo tee -a /etc/ld.so.conf.d/custom-libs.conf
          echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/custom-libs.conf
          sudo ldconfig

      # Clean up any precompiled objects
      - name: Clean Up Precompiled Files
        run: |
          find src -name "*.o" -type f -delete
          find src -name "*.so" -type f -delete

      - name: Install Key R Packages
        run: |
          Rscript -e 'install.packages(c("remotes", "desc", "devtools"))'

      - name: Install Dependencies with Retries
        run: |
          for i in {1..3}; do Rscript -e 'remotes::install_deps(dependencies = TRUE)' && break || sleep 15; done

      # Build the package with explicit flags
      - name: Build Package and Binary
        env:
          PKG_CFLAGS: "-fopenmp"
          PKG_LIBS: "-lgsl -lgslcblas -fopenmp -lm -lR"
        run: |
          R CMD INSTALL --configure-vars="PKG_CFLAGS='-fopenmp' PKG_LIBS='-lgsl -lgslcblas -fopenmp -lm -lR'" .

      - name: Get Version from DESCRIPTION
        id: get_version
        run: |
          version=$(Rscript -e 'cat(desc::desc_get_version())')
          echo "version=$version" >> $GITHUB_ENV

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.version }}"
          name: "v${{ env.version }} Release"
          body: "Release notes for version ${{ env.version }}."
          files: ${{ github.workspace }}/tidBIT_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
