name: R package binary build

on:
  push:
    branches:
      - main  # Change to the branch where your code resides
  pull_request:
    branches:
      - main  # Build for pull requests too

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up R on the runner
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install Pandoc (only if you're building vignettes)
      - name: Install Pandoc
        run: |
          choco install pandoc
          pandoc --version

      # Step 4: Install R dependencies
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      # Step 5: Build the package and binary, then list files
      - name: Build package and binary
        run: |
          Rscript -e 'devtools::build(binary = TRUE)'  # Build the binary package
          ls -lh  # List all files to check if a .zip file was created and where

      # Step 6: Install Rtools (for Windows)
      - name: Install Rtools
        run: |
          Rscript -e 'install.packages("pkgbuild")'
          Rscript -e 'pkgbuild::check_build_tools()'

      # Step 7: Upload the built binary package as an artifact
      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: tidBIT-windows-binary
          path: "*.zip"  # Assuming the binary is a .zip file; adjust if needed
