name: R package binary build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up R on the runner
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install Pandoc (if you're building vignettes)
      - name: Install Pandoc
        run: |
          choco install pandoc
          pandoc --version

      # Step 4: Install R dependencies
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      # Step 5: Build the package and binary
      - name: Build package and binary
        run: |
          Rscript -e 'devtools::build(binary = TRUE)'  # Build the binary package

      # Step 6: Get the Version from DESCRIPTION (using R)
      - name: Get Version from DESCRIPTION
        id: get_version
        run: |
          Rscript -e 'version <- desc::desc_get_version(); cat(paste0("::set-output name=version::", version, "\n"))'
      
      # Step 7: Create or Update GitHub Release and Upload Binary
      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"  # Dynamically use the version
          name: "v${{ steps.get_version.outputs.version }} Release"
          body: "Release notes for version ${{ steps.get_version.outputs.version }}."
          files: D:/a/tidBIT/tidBIT_*.zip  # Specify the binary file to upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
