name: Build and Release Source Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies for R packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libtiff5-dev libjpeg-dev gdal-bin libgdal-dev

    - name: Install required R packages
      run: |
        echo "Installing R package dependencies"
        Rscript -e 'install.packages(c("flextable", "leaflet", "officer", "sf"), repos = "https://cran.rstudio.com")'

    - name: Create artifacts directory
      run: |
        echo "Creating artifacts directory"
        mkdir -p artifacts

    - name: Build source package
      run: |
        echo "Building tar.gz source package"
        R CMD build .

    - name: Build zip source package
      run: |
        echo "Building zip source package"
        zip -r artifacts/source.zip .

    - name: Move tar.gz to artifacts
      run: |
        echo "Moving tar.gz source package to artifacts"
        mv *.tar.gz artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tidBIT-source-packages
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: artifacts/*
