name: R Package Source Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-source:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Create source package
      - name: Install R package dependencies
        run: |
          echo "Installing required R package dependencies"
          Rscript -e 'install.packages(c("remotes", "corrplot", "dplyr", "flextable", "ggplot2", "GGally", "leaflet", "lubridate", "officer", "patchwork", "readxl", "rstudioapi", "scales", "sf", "tibble", "tidyr", "tidyselect", "zeallot", "openxlsx"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          
      - name: Build source package
        run: |
          echo "Creating artifacts directory"
          mkdir -p artifacts

          echo "Building tar.gz source package"
          R CMD build .

          echo "Building zip source package"
          zip -r artifacts/source.zip .

          echo "Moving tar.gz source package to artifacts"
          mv *.tar.gz artifacts/
        shell: bash
        env:
          R_LIBS_USER: /home/runner/work/_temp/Library
          TZ: UTC
          _R_CHECK_SYSTEM_CLOCK_: FALSE
          NOT_CRAN: true


      # Step 4: Upload source artifacts
      - name: Upload source artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source-artifacts
          path: artifacts/

  create-release:
    needs: package-source
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Upload to GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Release v${{ github.run_number }}"
          body: |
            ### Release Notes
            - Includes source package in `.tar.gz` and `.zip` formats.
          files: |
            artifacts/source.zip
            artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
