name: R package binary build 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Configure CRAN mirror to RSPM
      - name: Configure CRAN mirror to RSPM
        run: |
          echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/jammy/latest"))' >> ~/.Rprofile

      # Install system dependencies for GSL, OpenMP, and build tools
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgsl-dev libomp-dev libudunits2-dev libproj-dev libgdal-dev build-essential gcc gfortran

      # Debugging Library Paths
      - name: Debug Libraries
        run: |
          echo "Checking GSL library:"
          ldconfig -p | grep gsl || echo "GSL library not found"
          echo "Checking OpenMP library:"
          ldconfig -p | grep omp || echo "OpenMP library not found"

      - name: Clean Up Precompiled Files
        run: |
          find src -name "*.o" -type f -delete
          find src -name "*.so" -type f -delete

      - name: Install Key R Packages
        run: |
          Rscript -e 'install.packages(c("remotes", "desc", "devtools"))'

      - name: Install Dependencies with Retries
        run: |
          for i in {1..3}; do Rscript -e 'remotes::install_deps(dependencies = TRUE)' && break || sleep 15; done

      - name: Build Package and Binary
        env:
          OS_TYPE: linux  # Explicitly set to 'linux' for GitHub Actions
          PKG_CFLAGS: "-fopenmp"
          PKG_LIBS: "-L/lib/x86_64-linux-gnu -lgsl -lgslcblas -fopenmp -lm"
          LD_LIBRARY_PATH: "/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
        run: |
          R CMD INSTALL --configure-vars="PKG_CFLAGS='-fopenmp' PKG_LIBS='-L/lib/x86_64-linux-gnu -lgsl -lgslcblas -fopenmp -lm'" --debug .

      - name: Get Version from DESCRIPTION
        id: get_version
        run: |
          version=$(Rscript -e 'cat(desc::desc_get_version())')
          echo "version=$version" >> $GITHUB_ENV

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.version }}"
          name: "v${{ env.version }} Release"
          body: "Release notes for version ${{ env.version }}."
          files: ${{ github.workspace }}/tidBIT_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
