name: R package binary build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Configure CRAN mirror to RSPM
      - name: Configure CRAN mirror to RSPM
        run: |
          echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/jammy/latest"))' >> ~/.Rprofile

      # Install system dependencies for GSL, OpenMP, and build tools
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgsl-dev \
            libomp-dev \
            libudunits2-dev \
            libproj-dev \
            libgdal-dev \
            build-essential \
            gcc \
            gfortran

      - name: Build Package for Windows
        run: |
          mkdir -p artifacts  # Create an output directory
          Rscript -e "devtools::build(binary = TRUE, path = 'artifacts')"

      - name: Build Package for macOS
        runs-on: macos-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up R
            uses: r-lib/actions/setup-r@v2

          - name: Build macOS Binary
            run: |
              mkdir -p artifacts  # Create an output directory
              Rscript -e "devtools::build(binary = TRUE, path = 'artifacts')"

          - name: Debug macOS Built Files
            run: |
              echo "Listing artifacts directory:"
              ls -l artifacts

      - name: Debug Built Files (Linux/Windows)
        run: |
          echo "Listing artifacts directory:"
          ls -l artifacts

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.version }}"
          name: "v${{ env.version }} Release"
          body: "Release notes for version ${{ env.version }}."
          files: |
            artifacts/tidBIT_*.zip
            artifacts/tidBIT_*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
