name: R package binary build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up R on the runner
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install Pandoc (only if you are building vignettes)
      - name: Install Pandoc
        run: |
          choco install pandoc
          pandoc --version

      # Step 4: Install R dependencies
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      # Step 5: Build the package (with or without vignettes)
      - name: Build package
        run: |
          Rscript -e 'devtools::build(vignettes = TRUE)'  # Set to FALSE if you don't want vignettes

      # Step 6: Install Rtools (for Windows)
      - name: Install Rtools
        run: |
          Rscript -e 'install.packages("pkgbuild")'
          Rscript -e 'pkgbuild::check_build_tools()'

      # Step 7: Build Windows binary package using Rscript
      - name: Build Windows binary
        run: |
          Rscript -e 'devtools::install(build = TRUE)'  # This replaces the R CMD INSTALL --build . command

      # Step 8: Upload the built binary package as an artifact
      - name: Upload Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: tidBIT-windows-binary
          path: "*.zip"  # Upload the binary package
